# Generated by Django 4.2 on 2025-10-08 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vehicle_status_vehiclelocation_aiinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managed_routes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='std_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='vip_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='route_images/'),
        ),
    ]
