# Generated by Django 4.2 on 2025-11-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_feedback_unique_together_alter_feedback_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclelocation',
            old_name='timestamp',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('delayed', 'Delayed'), ('offline', 'Offline')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='main.vehicle'),
        ),
    ]
