# Generated by Django 4.2 on 2025-11-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_timestamp_vehiclelocation_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='status',
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle'),
        ),
    ]
