"""
Django settings for dlamss_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v-wpbn$=-)bxjcp7itr-b$ata=%#u%$ev^7t67h&b+tjv4%$-c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'channels',  # 👈 NEW: For WebSockets (GPS real-time)
]

# 👈 NEW: ASGI config for WebSockets (GPS)
ASGI_APPLICATION = 'dlamss_project.asgi.application'  # Create asgi.py if not exists (see below)

JAZZMIN_SETTINGS = {
     "site_title": "Digital Larry Adda Admin",
    "site_header": "Digital Larry Adda Dashboard",
    "site_brand": "Digital Larry Adda",
    "welcome_sign": "Welcome to Digital Larry Adda Admin Panel",
    "copyright": "Digital Larry Adda",
    "search_model": "auth.User",

    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        
    ],

    "usermenu_links": [
        {"name": "Support", "url": "https://support.example.com", "new_window": True},
    ],
     
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "yourappname"],

    "icons": {
        "auth": "fas fa-users",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users-cog",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-angle-right",

    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
}


JAZZMIN_UI_TWEAKS = {
    # Theme base (optional)
    "theme": "flatly",  # You can also try: lux, litera, superhero, etc.

    # Navbar (Top Bar)
    "navbar_small_text": False,
    "navbar_fixed": True,
    "navbar_color": "navbar-dark bg-primary",  # Dark text on blue

    # Sidebar (Left Menu)
    "sidebar_fixed": True,
    "sidebar_small_text": False,
    "sidebar_color": "sidebar-dark-navy",  # Professional dark navy look
    "brand_colour": "navbar-dark bg-primary",

    # Footer
    "footer_fixed": False,
    "footer_small_text": False,

    # Body
    "body_small_text": False,

    # Button Style
    "button_classes": {
        "primary": "btn btn-outline-primary",
        "secondary": "btn btn-outline-secondary",
        "info": "btn btn-outline-info",
        "warning": "btn btn-outline-warning",
        "danger": "btn btn-outline-danger",
        "success": "btn btn-outline-success"
    },

    # Custom text sizes (optional)
    "text_classes": {
        "h1": "text-primary",
        "h2": "text-secondary",
    }
}
 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dlamss_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 👈 NEW: Channel layers for WebSockets (GPS) - Use Redis in production
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],  # Start Redis: brew install redis (Mac) or sudo apt install redis-server (Linux)
        },
    },
}

WSGI_APPLICATION = 'dlamss_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = '/admin/'


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

AUTH_USER_MODEL = 'main.CustomUser'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py کے آخر میں یہ دو لائنیں add کرو:

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 👈 NEW: Email config for notifications (vehicle breakdown)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Or your SMTP host
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'  # Replace with your Gmail
EMAIL_HOST_PASSWORD = 'your-app-password'  # Use Gmail App Password (not regular password)

OPENROUTER_API_KEY = "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"
